/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ExchangeRate {
    status: string;
    source: string;
    rate: number;
    message: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserPortfolio {
    totalValue: number;
    assets: Array<Asset>;
    lastModified: Time;
    historicalData: Array<HistoricalDataPoint>;
    annualReturn: number;
    totalChange24h: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DailyHistoryState {
    lastRecordedDate: string;
    lastRecordedTimestamp: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Asset {
    id: string;
    apiStatus: string;
    name: string;
    type: string;
    lastUpdated: Time;
    customPrice?: number;
    isStaked: boolean;
    priceChange24h: number;
    quantity: number;
    annualYield: number;
    price: number;
    stakedAmount: number;
}
export interface HistoricalDataPoint {
    value: number;
    date: string;
}
export interface ApiStatus {
    status: string;
    message: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    themePreference: string;
    displayCurrency: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addSharedHistoricalDataPoint(date: string, value: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cachePriceData(asset: string, data: string): Promise<void>;
    calculateAnnualReturn(currentValue: number): Promise<number>;
    calculatePortfolioChange24h(assets: Array<Asset>): Promise<number>;
    calculateTotalPortfolioValue(assets: Array<Asset>): Promise<number>;
    checkAndAppendDailyHistoricalPoint(): Promise<void>;
    fetchCryptoPrices(): Promise<string>;
    fetchExchangeRates(): Promise<string>;
    fetchStockPrices(): Promise<string>;
    getApiStatus(): Promise<Array<[string, ApiStatus]>>;
    getCallerPortfolio(): Promise<UserPortfolio>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyTrackingStatus(): Promise<DailyHistoryState>;
    getDefaultAssets(): Promise<Array<Asset>>;
    getExchangeRate(): Promise<ExchangeRate>;
    getExchangeRateStatus(): Promise<string>;
    getLastUpdateTime(): Promise<string>;
    getSharedHistoricalData(): Promise<Array<HistoricalDataPoint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    healthCheck(): Promise<string>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    resetPortfolioToDefaults(): Promise<void>;
    saveCallerPortfolio(portfolio: UserPortfolio): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setExchangeRate(rate: number, source: string, status: string, message: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAllPrices(): Promise<void>;
    updateApiStatus(assetId: string, status: string, message: string): Promise<void>;
    updateAssetCustomPrice(assetId: string, customPrice: number | null): Promise<void>;
    updateAssetQuantity(assetId: string, newQuantity: number): Promise<void>;
    updateLastFetchTime(): Promise<void>;
}
import type { Asset as _Asset, HistoricalDataPoint as _HistoricalDataPoint, Time as _Time, UserPortfolio as _UserPortfolio, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addSharedHistoricalDataPoint(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSharedHistoricalDataPoint(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSharedHistoricalDataPoint(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cachePriceData(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cachePriceData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cachePriceData(arg0, arg1);
            return result;
        }
    }
    async calculateAnnualReturn(arg0: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAnnualReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAnnualReturn(arg0);
            return result;
        }
    }
    async calculatePortfolioChange24h(arg0: Array<Asset>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePortfolioChange24h(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePortfolioChange24h(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async calculateTotalPortfolioValue(arg0: Array<Asset>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalPortfolioValue(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalPortfolioValue(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async checkAndAppendDailyHistoricalPoint(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndAppendDailyHistoricalPoint();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndAppendDailyHistoricalPoint();
            return result;
        }
    }
    async fetchCryptoPrices(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCryptoPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCryptoPrices();
            return result;
        }
    }
    async fetchExchangeRates(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchExchangeRates();
            return result;
        }
    }
    async fetchStockPrices(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchStockPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchStockPrices();
            return result;
        }
    }
    async getApiStatus(): Promise<Array<[string, ApiStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiStatus();
            return result;
        }
    }
    async getCallerPortfolio(): Promise<UserPortfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPortfolio();
                return from_candid_UserPortfolio_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPortfolio();
            return from_candid_UserPortfolio_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyTrackingStatus(): Promise<DailyHistoryState> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTrackingStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTrackingStatus();
            return result;
        }
    }
    async getDefaultAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultAssets();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultAssets();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeRate(): Promise<ExchangeRate> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRate();
            return result;
        }
    }
    async getExchangeRateStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRateStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRateStatus();
            return result;
        }
    }
    async getLastUpdateTime(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdateTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdateTime();
            return result;
        }
    }
    async getSharedHistoricalData(): Promise<Array<HistoricalDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedHistoricalData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedHistoricalData();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetPortfolioToDefaults(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPortfolioToDefaults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPortfolioToDefaults();
            return result;
        }
    }
    async saveCallerPortfolio(arg0: UserPortfolio): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerPortfolio(to_candid_UserPortfolio_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerPortfolio(to_candid_UserPortfolio_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setExchangeRate(arg0: number, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExchangeRate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExchangeRate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAllPrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAllPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAllPrices();
            return result;
        }
    }
    async updateApiStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApiStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApiStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAssetCustomPrice(arg0: string, arg1: number | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetCustomPrice(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetCustomPrice(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAssetQuantity(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetQuantity(arg0, arg1);
            return result;
        }
    }
    async updateLastFetchTime(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastFetchTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastFetchTime();
            return result;
        }
    }
}
function from_candid_Asset_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserPortfolio_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPortfolio): UserPortfolio {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: number;
    assets: Array<_Asset>;
    lastModified: _Time;
    historicalData: Array<_HistoricalDataPoint>;
    annualReturn: number;
    totalChange24h: number;
}): {
    totalValue: number;
    assets: Array<Asset>;
    lastModified: Time;
    historicalData: Array<HistoricalDataPoint>;
    annualReturn: number;
    totalChange24h: number;
} {
    return {
        totalValue: value.totalValue,
        assets: from_candid_vec_n15(_uploadFile, _downloadFile, value.assets),
        lastModified: value.lastModified,
        historicalData: value.historicalData,
        annualReturn: value.annualReturn,
        totalChange24h: value.totalChange24h
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    apiStatus: string;
    name: string;
    type: string;
    lastUpdated: _Time;
    customPrice: [] | [number];
    isStaked: boolean;
    priceChange24h: number;
    quantity: number;
    annualYield: number;
    price: number;
    stakedAmount: number;
}): {
    id: string;
    apiStatus: string;
    name: string;
    type: string;
    lastUpdated: Time;
    customPrice?: number;
    isStaked: boolean;
    priceChange24h: number;
    quantity: number;
    annualYield: number;
    price: number;
    stakedAmount: number;
} {
    return {
        id: value.id,
        apiStatus: value.apiStatus,
        name: value.name,
        type: value.type,
        lastUpdated: value.lastUpdated,
        customPrice: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.customPrice)),
        isStaked: value.isStaked,
        priceChange24h: value.priceChange24h,
        quantity: value.quantity,
        annualYield: value.annualYield,
        price: value.price,
        stakedAmount: value.stakedAmount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Asset_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): _Asset {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserPortfolio_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPortfolio): _UserPortfolio {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    apiStatus: string;
    name: string;
    type: string;
    lastUpdated: Time;
    customPrice?: number;
    isStaked: boolean;
    priceChange24h: number;
    quantity: number;
    annualYield: number;
    price: number;
    stakedAmount: number;
}): {
    id: string;
    apiStatus: string;
    name: string;
    type: string;
    lastUpdated: _Time;
    customPrice: [] | [number];
    isStaked: boolean;
    priceChange24h: number;
    quantity: number;
    annualYield: number;
    price: number;
    stakedAmount: number;
} {
    return {
        id: value.id,
        apiStatus: value.apiStatus,
        name: value.name,
        type: value.type,
        lastUpdated: value.lastUpdated,
        customPrice: value.customPrice ? candid_some(value.customPrice) : candid_none(),
        isStaked: value.isStaked,
        priceChange24h: value.priceChange24h,
        quantity: value.quantity,
        annualYield: value.annualYield,
        price: value.price,
        stakedAmount: value.stakedAmount
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: number;
    assets: Array<Asset>;
    lastModified: Time;
    historicalData: Array<HistoricalDataPoint>;
    annualReturn: number;
    totalChange24h: number;
}): {
    totalValue: number;
    assets: Array<_Asset>;
    lastModified: _Time;
    historicalData: Array<_HistoricalDataPoint>;
    annualReturn: number;
    totalChange24h: number;
} {
    return {
        totalValue: value.totalValue,
        assets: to_candid_vec_n10(_uploadFile, _downloadFile, value.assets),
        lastModified: value.lastModified,
        historicalData: value.historicalData,
        annualReturn: value.annualReturn,
        totalChange24h: value.totalChange24h
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Asset>): Array<_Asset> {
    return value.map((x)=>to_candid_Asset_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
