/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Asset = IDL.Record({
  'id' : IDL.Text,
  'apiStatus' : IDL.Text,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'lastUpdated' : Time,
  'customPrice' : IDL.Opt(IDL.Float64),
  'isStaked' : IDL.Bool,
  'priceChange24h' : IDL.Float64,
  'quantity' : IDL.Float64,
  'annualYield' : IDL.Float64,
  'price' : IDL.Float64,
  'stakedAmount' : IDL.Float64,
});
export const ApiStatus = IDL.Record({
  'status' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const HistoricalDataPoint = IDL.Record({
  'value' : IDL.Float64,
  'date' : IDL.Text,
});
export const UserPortfolio = IDL.Record({
  'totalValue' : IDL.Float64,
  'assets' : IDL.Vec(Asset),
  'lastModified' : Time,
  'historicalData' : IDL.Vec(HistoricalDataPoint),
  'annualReturn' : IDL.Float64,
  'totalChange24h' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'themePreference' : IDL.Text,
  'displayCurrency' : IDL.Text,
});
export const DailyHistoryState = IDL.Record({
  'lastRecordedDate' : IDL.Text,
  'lastRecordedTimestamp' : Time,
});
export const ExchangeRate = IDL.Record({
  'status' : IDL.Text,
  'source' : IDL.Text,
  'rate' : IDL.Float64,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSharedHistoricalDataPoint' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cachePriceData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'calculateAnnualReturn' : IDL.Func([IDL.Float64], [IDL.Float64], ['query']),
  'calculatePortfolioChange24h' : IDL.Func(
      [IDL.Vec(Asset)],
      [IDL.Float64],
      ['query'],
    ),
  'calculateTotalPortfolioValue' : IDL.Func(
      [IDL.Vec(Asset)],
      [IDL.Float64],
      ['query'],
    ),
  'checkAndAppendDailyHistoricalPoint' : IDL.Func([], [], []),
  'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
  'fetchExchangeRates' : IDL.Func([], [IDL.Text], []),
  'fetchStockPrices' : IDL.Func([], [IDL.Text], []),
  'getApiStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApiStatus))],
      ['query'],
    ),
  'getCallerPortfolio' : IDL.Func([], [UserPortfolio], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTrackingStatus' : IDL.Func([], [DailyHistoryState], ['query']),
  'getDefaultAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getExchangeRate' : IDL.Func([], [ExchangeRate], ['query']),
  'getExchangeRateStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getLastUpdateTime' : IDL.Func([], [IDL.Text], ['query']),
  'getSharedHistoricalData' : IDL.Func(
      [],
      [IDL.Vec(HistoricalDataPoint)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetPortfolioToDefaults' : IDL.Func([], [], []),
  'saveCallerPortfolio' : IDL.Func([UserPortfolio], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setExchangeRate' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAllPrices' : IDL.Func([], [], []),
  'updateApiStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAssetCustomPrice' : IDL.Func([IDL.Text, IDL.Opt(IDL.Float64)], [], []),
  'updateAssetQuantity' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateLastFetchTime' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'apiStatus' : IDL.Text,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'lastUpdated' : Time,
    'customPrice' : IDL.Opt(IDL.Float64),
    'isStaked' : IDL.Bool,
    'priceChange24h' : IDL.Float64,
    'quantity' : IDL.Float64,
    'annualYield' : IDL.Float64,
    'price' : IDL.Float64,
    'stakedAmount' : IDL.Float64,
  });
  const ApiStatus = IDL.Record({
    'status' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const HistoricalDataPoint = IDL.Record({
    'value' : IDL.Float64,
    'date' : IDL.Text,
  });
  const UserPortfolio = IDL.Record({
    'totalValue' : IDL.Float64,
    'assets' : IDL.Vec(Asset),
    'lastModified' : Time,
    'historicalData' : IDL.Vec(HistoricalDataPoint),
    'annualReturn' : IDL.Float64,
    'totalChange24h' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'themePreference' : IDL.Text,
    'displayCurrency' : IDL.Text,
  });
  const DailyHistoryState = IDL.Record({
    'lastRecordedDate' : IDL.Text,
    'lastRecordedTimestamp' : Time,
  });
  const ExchangeRate = IDL.Record({
    'status' : IDL.Text,
    'source' : IDL.Text,
    'rate' : IDL.Float64,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSharedHistoricalDataPoint' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cachePriceData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'calculateAnnualReturn' : IDL.Func([IDL.Float64], [IDL.Float64], ['query']),
    'calculatePortfolioChange24h' : IDL.Func(
        [IDL.Vec(Asset)],
        [IDL.Float64],
        ['query'],
      ),
    'calculateTotalPortfolioValue' : IDL.Func(
        [IDL.Vec(Asset)],
        [IDL.Float64],
        ['query'],
      ),
    'checkAndAppendDailyHistoricalPoint' : IDL.Func([], [], []),
    'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
    'fetchExchangeRates' : IDL.Func([], [IDL.Text], []),
    'fetchStockPrices' : IDL.Func([], [IDL.Text], []),
    'getApiStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApiStatus))],
        ['query'],
      ),
    'getCallerPortfolio' : IDL.Func([], [UserPortfolio], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTrackingStatus' : IDL.Func([], [DailyHistoryState], ['query']),
    'getDefaultAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getExchangeRate' : IDL.Func([], [ExchangeRate], ['query']),
    'getExchangeRateStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getLastUpdateTime' : IDL.Func([], [IDL.Text], ['query']),
    'getSharedHistoricalData' : IDL.Func(
        [],
        [IDL.Vec(HistoricalDataPoint)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetPortfolioToDefaults' : IDL.Func([], [], []),
    'saveCallerPortfolio' : IDL.Func([UserPortfolio], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setExchangeRate' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAllPrices' : IDL.Func([], [], []),
    'updateApiStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAssetCustomPrice' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Float64)],
        [],
        [],
      ),
    'updateAssetQuantity' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateLastFetchTime' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };