/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiStatus {
  'status' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Asset {
  'id' : string,
  'apiStatus' : string,
  'name' : string,
  'type' : string,
  'lastUpdated' : Time,
  'customPrice' : [] | [number],
  'isStaked' : boolean,
  'priceChange24h' : number,
  'quantity' : number,
  'annualYield' : number,
  'price' : number,
  'stakedAmount' : number,
}
export interface DailyHistoryState {
  'lastRecordedDate' : string,
  'lastRecordedTimestamp' : Time,
}
export interface ExchangeRate {
  'status' : string,
  'source' : string,
  'rate' : number,
  'message' : string,
  'timestamp' : Time,
}
export interface HistoricalDataPoint { 'value' : number, 'date' : string }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPortfolio {
  'totalValue' : number,
  'assets' : Array<Asset>,
  'lastModified' : Time,
  'historicalData' : Array<HistoricalDataPoint>,
  'annualReturn' : number,
  'totalChange24h' : number,
}
export interface UserProfile {
  'name' : string,
  'themePreference' : string,
  'displayCurrency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addSharedHistoricalDataPoint' : ActorMethod<[string, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cachePriceData' : ActorMethod<[string, string], undefined>,
  'calculateAnnualReturn' : ActorMethod<[number], number>,
  'calculatePortfolioChange24h' : ActorMethod<[Array<Asset>], number>,
  'calculateTotalPortfolioValue' : ActorMethod<[Array<Asset>], number>,
  'checkAndAppendDailyHistoricalPoint' : ActorMethod<[], undefined>,
  'fetchCryptoPrices' : ActorMethod<[], string>,
  'fetchExchangeRates' : ActorMethod<[], string>,
  'fetchStockPrices' : ActorMethod<[], string>,
  'getApiStatus' : ActorMethod<[], Array<[string, ApiStatus]>>,
  'getCallerPortfolio' : ActorMethod<[], UserPortfolio>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTrackingStatus' : ActorMethod<[], DailyHistoryState>,
  'getDefaultAssets' : ActorMethod<[], Array<Asset>>,
  'getExchangeRate' : ActorMethod<[], ExchangeRate>,
  'getExchangeRateStatus' : ActorMethod<[], string>,
  'getLastUpdateTime' : ActorMethod<[], string>,
  'getSharedHistoricalData' : ActorMethod<[], Array<HistoricalDataPoint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetPortfolioToDefaults' : ActorMethod<[], undefined>,
  'saveCallerPortfolio' : ActorMethod<[UserPortfolio], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setExchangeRate' : ActorMethod<[number, string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAllPrices' : ActorMethod<[], undefined>,
  'updateApiStatus' : ActorMethod<[string, string, string], undefined>,
  'updateAssetCustomPrice' : ActorMethod<[string, [] | [number]], undefined>,
  'updateAssetQuantity' : ActorMethod<[string, number], undefined>,
  'updateLastFetchTime' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];